### ISSUE TITLE
Uppercase properties keys for planes

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleSpecs#22]
https://github.com/speckleworks/SpeckleSpecs/blob/cf5037ccdadf877eca748cf968ee0a4b626ed848/SpeckleV1OpenApiSpecs.yaml#L1390-L1401

Origin, Normal, Xdir, Ydir should be lowercase

**Comment by didimitrie** [comment]
you fixed this, didn't you @mswaidan? I'm going to close.
